EXPERIMENT_PARAMS:
 
  num_trials: 50
  test_pct: 0.75
  rngseed: 12345
  DW_size: 32
  DWLG_size: 64
  default_size: 1024

  model_list: ['SVC']
  prefix: 'clf'
  exp_type: "classification"
  score: 'balanced_accuracy'
  output_path: "../results"
  tdc_path: "../data/raw/tdc/"


FEATURE_PARAMS:
  feature_type: 'all'
  J_v: 2
  maxMoment_v: 3
  central_v: False
  J_e: 2
  maxMoment_e: 3
  central_e: False


MODEL_PARAMS:
  SVC:
    C:
      type: "float"
      min: 1
      max: 1
      step: 1
      logspace: False
    penalty:
      type: "list"
      values: ['l1','l2']
    dual:
      type: "list"
      values: ["auto"]
  KNN:
    n_neighbors:
      type: "int"
      min: 2
      max: 15
      step: 1
  LR:
    penalty:
      type: "list"
      values: ['l1']
    solver:
      type: "list"
      values: ['saga']
    C:
      type: "float"
      min: -2
      max: 2
      step: 40
      logspace: True








