EXPERIMENT_PARAMS:
 
  num_trials: 100
  test_pct: 0.8
  rngseed: 12345
  short_size: 32
  long_size: 1024

  model_list: ['Ridge','OLS']
  prefix: 'regr'
  exp_type: "regression"
  score: 'neg_mean_absolute_error'
  output_path: "../results"
  tdc_path: "../data/raw/tdc/"


FEATURE_PARAMS:
  feature_type: 'morgan_short'
  standardize_feats: True
  J_v: 2
  maxMoment_v: 3
  central_v: False
  J_e: 2
  maxMoment_e: 3
  central_e: False


MODEL_PARAMS:
  RIDGE:
    names: ['alpha']
    mins: [0.01]
    maxs: [100]
    steps: [10]
    logspaces: [True]
    int_only: [False]
  OLS:
    names: []
    mins: []
    maxs: []
    steps: []
    logspaces: []
    int_only: []
  RFR:
    names: ['n_estimators','max_depth']
    mins: [50, 2]
    maxs: [200,10]
    steps: [10, 10]
    logspaces: [False, False]
    int_only: [True, True]






