EXPERIMENT_PARAMS:
 
  num_trials: 100
  test_pct: 0.75
  rngseed: 12345
  short_size: 32
  long_size: 1024

  model_list: ['Ridge','OLS','RFR']
  prefix: 'regr'
  exp_type: "regression"
  score: 'neg_mean_absolute_error'
  output_path: "../results"
  tdc_path: "../data/raw/tdc/"


FEATURE_PARAMS:
  feature_type: 'all'
  standardize_feats: True
  J_v: 2
  maxMoment_v: 3
  central_v: False
  J_e: 3
  maxMoment_e: 4
  central_e: False


MODEL_PARAMS:
  RIDGE:
    alpha:
      type: "float"
      min: -2
      max: 2
      step: 10
      logspace: True
  OLS:
  RFR:
    n_estimators:
      type: "int"
      min: 10
      max: 40
      step: 10 
    max_depth: 
      type: "int"
      min: 2
      max: 10
      step: 10
    min_samples_leaf:
      type: "list"
      values: [0.05, 0.10]






